---
- name: Create
  hosts: all
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:

    - when: True #server.changed | default(false) | bool
      block:

        - include_role:
            name: hera

#          containers.podman.podman_container:
#            name: test_container
#            state: started
#            image: localhost/ubi8-ssh-ansible
#            privileged: yes
#            rm: yes
#            ports:
#              - "8080:22"
        - name: Ensure hera_created_instances is defined"
          assert:
            that:
              - hera_created_instances is defined
              - hera_created_instances | length > 0
            quiet: true

        - name: Populate instance config dict
          set_fact:
            instance_conf_dict: {
              'instance': "instance",
              'address': "{{ item.address }}",
              'user': "{{ item.user }}",
              'port': "{{ item.port }}",
              'identity_file': "{{ item.ssh_key }}", }
          with_items: "{{ hera_created_instances  }}"
          register: instance_config_dict

        - debug:
            msg: "Create phase with {{ molecule_instance_config }}"

        - name: Convert instance config dict to a list
          set_fact:
            instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

        - name: Dump instance config
          copy:
            content: |
              {{ instance_conf | to_json | from_json | to_yaml }}
            dest: "{{ molecule_instance_config }}"

        - slurp:
            src: "{{ molecule_instance_config }}"
          register: res_conf

        - debug:
            msg: "{{ res_conf['content'] | b64decode }}"
