---
- name: Create
  hosts: all
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:

    - when: True #server.changed | default(false) | bool
      block:

        - command: >
            bash -x {{ hera_home }}/hera.sh run
          register: hera_run
          environment:
            BUILD_PODMAN_IMAGE: "{{ podman_image }}"
            CONTAINER_SERVER_HOSTNAME: "{{ container_server_hostname }}"
            CONTAINER_SERVER_IP: "{{ container_server_ip }}"
            WORKSPACE: "{{ workspace }}"
            JOB_NAME: ansible
            BUILD_ID: "{{ build_id }}"
            JENKINS_UID: 1001
            JENKINS_GUID: 1001
            JENKINS_HOME_DIR: "{{ jenkins_homedir }}"
            JENKINS_ACCOUNT_DIR: "{{ jenkins_account_dir }}"
            HERA_HOME: "{{ hera_home }}"
            HERA_SSH_KEY: "{{ ssh_key  }}"
            HERA_HOSTNAME: "{{ hera_hostname  }}"
            HERA_USERNAME: "{{ hera_user }}"
            HERA_DEBUG: "{{ hera_debug | default('True') }}"

        - debug:
            msg: "{{ hera_run }}"

#        - name: Ensure test container is running
#          containers.podman.podman_container:
#            name: test_container
#            state: started
#            image: localhost/ubi8-ssh-ansible
#            privileged: yes
#            rm: yes
#            ports:
#              - "8080:22"

        - name: Populate instance config dict
          set_fact:
            instance_conf_dict: {
              'instance': "instance",
              'address': "{{ item }}",
              'user': "rpelisse",
              'port': "8080",
              'identity_file': "{{ ssh_key }}", }
          with_items:
            - "127.0.0.1"
          register: instance_config_dict

        - debug:
            msg: "Create phase with {{ molecule_instance_config }}"

        - name: Convert instance config dict to a list
          set_fact:
            instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

        - name: Dump instance config
          copy:
            content: |
              {{ instance_conf | to_json | from_json | to_yaml }}
            dest: "{{ molecule_instance_config }}"

        - slurp:
            src: "{{ molecule_instance_config }}"
          register: res_conf

        - debug:
            msg: "{{ res_conf['content'] | b64decode }}"
